apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pet-deploy
  name: tashi-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pet-deploy
  template:
    metadata:
      labels:
        app: pet-deploy
    spec:
      containers:
      - image: thetashi777/tashi:2
        name: tashi
